version: '3.8'

services:
    database:
        container_name: database
        env_file:
            - ./.env.local
        image: mariadb:10.5.8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'K2ch7Kbtu4Br'
            MYSQL_DATABASE: 'keto_db'
            MYSQL_USER: 'marion'
            MYSQL_PASSWORD: '38lSrvb2pee0'
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - db_data:/var/lib/mysql:cached

    php:
        container_name: php
        env_file:
            - ./.env.local
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - '${PHP_PORT}:9000'
        user: 'www-data'
        volumes:
            - .:/var/www/${PROJECT_NAME}
        environment:
            - TZ=Europe/Paris
        working_dir: /var/www/${PROJECT_NAME}
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - database

    nginx:
        container_name: nginx
        env_file:
            - ./.env.local
        image: nginx:stable-alpine
        ports:
            - '${HTTP_PORT}:80'
        volumes:
            - .:/var/www/${PROJECT_NAME}
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=Europe/Paris
        working_dir: /var/www
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - php
            - database

volumes:
    db_data:
        driver: local
